'use strict';
const $=s=>document.querySelector(s),escapeHtml=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=n=>n==null?'—':Number(n).toLocaleString('id-ID',{maximumFractionDigits:2});
const fields=[['code','Kode item',0],['description','Uraian',1],['unit','Satuan',3],['qty','Qty referensi',4],['price','Unit price',5],['amount','Nilai sumber',6]];
let workbook=null,sourceName='',parsed={items:[],issues:[],skipped:[]},wo=[],selected=new Set(),collapsed=new Set();
function status(s){$('#status').textContent=s}
function tab(name){if($('#projects'))$('#projects').hidden=name!=='projects';if($('#contractContext'))$('#contractContext').hidden=name==='projects';$('#master').hidden=name!=='master';$('#wo').hidden=name!=='wo';document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));}
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>tab(b.dataset.tab));
function mapping(){const sheet=workbook?.Sheets[$('#sheet').value],cols=sheet?.['!ref']?XLSX.utils.decode_range(sheet['!ref']).e.c+1:9;$('#mapping').innerHTML=fields.map(([key,label,defaultCol])=>`<label>${label}<select data-map="${key}"><option value="-1">Tidak ada</option>${Array.from({length:Math.min(cols,100)},(_,c)=>`<option value="${c}" ${c===defaultCol?'selected':''}>Kolom ${XLSX.utils.encode_col(c)}</option>`).join('')}</select></label>`).join('')}
$('#importToggle').onclick=()=>$('#importPanel').hidden=!$('#importPanel').hidden;
$('#excelFile').onchange=async e=>{const file=e.target.files[0];if(!file)return;if(file.size>20*1024*1024){status('Batas file 20 MB.');return}try{if(!globalThis.XLSX)throw Error('Pembaca Excel belum tersedia');workbook=XLSX.read(await file.arrayBuffer(),{type:'array'});sourceName=file.name;$('#sheet').innerHTML=workbook.SheetNames.map(n=>`<option>${escapeHtml(n)}</option>`).join('');$('#sheet').disabled=false;$('#preview').disabled=false;mapping();status('File terbaca. Periksa sheet, baris pertama, dan pemetaan kolom.')}catch(err){workbook=null;$('#preview').disabled=true;status('Gagal membaca Excel: '+err.message)}};
$('#sheet').onchange=mapping;
$('#preview').onclick=()=>{try{if(!workbook)return;const map=Object.fromEntries([...document.querySelectorAll('[data-map]')].map(el=>[el.dataset.map,Number(el.value)])),mapped=Object.values(map).filter(x=>x>=0);if(new Set(mapped).size!==mapped.length)throw Error('Setiap kolom hanya boleh dipetakan sekali');if(['description','unit','price'].some(k=>map[k]<0))throw Error('Uraian, satuan, dan harga wajib dipetakan');const first=Number($('#firstRow').value);if(!Number.isInteger(first)||first<1)throw Error('Baris pertama tidak valid');if(wo.length&&!confirm('Preview master baru akan mengosongkan draft WO saat ini. Lanjut?'))return;const rows=XLSX.utils.sheet_to_json(workbook.Sheets[$('#sheet').value],{header:1,raw:true,defval:null,blankrows:true});parsed=Commercial.parse(rows,map,{start:first-1,locale:$('#locale').value});wo=[];selected.clear();collapsed.clear();renderMaster();renderWo();status('Preview siap. Tinjau kelompok induk dan peringatan sebelum menyimpan draft.')}catch(err){status(err.message)}};
function visible(item){let node=item;while(node?.parentId){if(collapsed.has(node.parentId))return false;node=parsed.items.find(i=>i.id===node.parentId)}return true}
function renderMaster(){const items=parsed.items,search=$('#search').value.toLowerCase(),errors=parsed.issues.filter(i=>i.severity==='error');$('#summary').textContent=`${items.filter(i=>i.rowKind==='ITEM').length} item komersial · ${items.filter(i=>i.rowKind==='GROUP').length} kelompok · ${parsed.skipped.length} baris ringkasan dilewati · ${errors.length} error`;$('#issues').innerHTML=parsed.issues.length?`<details><summary>${parsed.issues.length} catatan validasi</summary><ul>${parsed.issues.map(i=>`<li>Baris ${i.row}: ${escapeHtml(i.message)}</li>`).join('')}</ul></details>`:'';$('#exportMaster').disabled=!items.length||!!errors.length;$('#addWo').disabled=!items.length||!!errors.length||$('#contractType').value==='LUMPSUM';const groups=items.filter(i=>i.rowKind==='GROUP');$('#masterRows').innerHTML=items.filter(i=>search?(i.code+' '+i.description).toLowerCase().includes(search):visible(i)).map(i=>{const parents=`<select class="parent" data-parent="${i.id}" aria-label="Induk ${escapeHtml(i.code)}"><option value="">Tanpa induk</option>${groups.filter(g=>g.id!==i.id).map(g=>`<option value="${g.id}" ${g.id===i.parentId?'selected':''}>${escapeHtml(g.code+' · '+g.description)}</option>`).join('')}</select>`;if(i.rowKind==='GROUP')return `<tr class="group"><td><button data-collapse="${i.id}" aria-label="Buka/tutup ${escapeHtml(i.description)}">${collapsed.has(i.id)?'▸':'▾'}</button></td><td>${i.code}${parents}</td><td colspan="5">${escapeHtml(i.description)}<small>Kelompok · baris ${i.sourceRow}</small></td></tr>`;return `<tr><td><input type="checkbox" data-select="${i.id}" ${selected.has(i.id)?'checked':''} aria-label="Pilih ${escapeHtml(i.code)}"></td><td>${escapeHtml(i.code)}${parents}</td><td class="scope">${escapeHtml(i.description)}<small>Baris ${i.sourceRow}</small></td><td><span class="rate">${i.rate}</span></td><td>${escapeHtml(i.unit)}</td><td class="num">${fmt(i.qty)}</td><td class="num" title="${escapeHtml(i.price)}">${fmt(i.price)}</td></tr>`}).join('')||'<tr><td colspan="7" class="empty">Tidak ada item ditemukan.</td></tr>';document.querySelectorAll('[data-select]').forEach(el=>el.onchange=()=>el.checked?selected.add(el.dataset.select):selected.delete(el.dataset.select));document.querySelectorAll('[data-collapse]').forEach(el=>el.onclick=()=>{collapsed.has(el.dataset.collapse)?collapsed.delete(el.dataset.collapse):collapsed.add(el.dataset.collapse);renderMaster()});document.querySelectorAll('[data-parent]').forEach(el=>el.onchange=()=>{const item=items.find(i=>i.id===el.dataset.parent),old=item.parentId;item.parentId=el.value||null;try{Commercial.ancestors(item,items);status('Induk diperbarui pada draft.')}catch(err){item.parentId=old;status('Induk ditolak: membentuk siklus.')}renderMaster()})}
$('#search').oninput=renderMaster;$('#contractType').onchange=()=>{renderMaster();status($('#contractType').value==='LUMPSUM'?'Alur WO tahap ini untuk Blanket Order; rincian Lumpsum tetap dapat dipreview.':'')};
$('#addWo').onclick=()=>{if(!selected.size){status('Pilih minimal satu item.');return}const pack=$('#packageName').value.trim()||'Paket 1';parsed.items.filter(i=>selected.has(i.id)).forEach(i=>{if(!wo.some(w=>w.sourceId===i.id&&w.package===pack))wo.push({id:crypto.randomUUID(),sourceId:i.id,code:i.code,description:i.description,unit:i.unit,price:i.price,rate:i.rate,path:Commercial.ancestors(i,parsed.items),package:pack,qty:1})});renderWo();tab('wo');status('Item ditambahkan ke draft WO. Sesuaikan qty dan paket pekerjaan.')};
function total(){const valid=wo.every(i=>Number.isFinite(i.qty)&&i.qty>0);$('#woTotal').textContent=valid?'Rp '+fmt(wo.reduce((s,i)=>s+i.price*i.qty,0)):'Periksa qty WO';$('#exportWo').disabled=!wo.length||!valid}
function renderWo(){$('#woCount').textContent=wo.length;$('#woRows').innerHTML=wo.map(i=>`<tr><td class="scope"><strong>${escapeHtml(i.code)}</strong> ${escapeHtml(i.description)}<small>${escapeHtml(i.path.join(' / '))}</small><label>Paket<input data-package="${i.id}" value="${escapeHtml(i.package)}"></label></td><td>${escapeHtml(i.unit)}</td><td><input class="qty" data-qty="${i.id}" aria-label="Qty ${escapeHtml(i.code)}" type="number" min="0.000001" step="any" value="${i.qty}"></td><td class="num">${fmt(i.price)}</td><td class="num" data-amount="${i.id}">${fmt(i.price*i.qty)}</td><td><button data-remove="${i.id}" aria-label="Hapus ${escapeHtml(i.code)}">Hapus</button></td></tr>`).join('')||'<tr><td colspan="6" class="empty">Pilih item pada Master Komersial untuk menyusun WO.</td></tr>';document.querySelectorAll('[data-qty]').forEach(el=>el.oninput=()=>{const i=wo.find(i=>i.id===el.dataset.qty);i.qty=el.value===''?NaN:Number(el.value);document.querySelector(`[data-amount="${i.id}"]`).textContent=Number.isFinite(i.qty)&&i.qty>0?fmt(i.qty*i.price):'Qty tidak valid';total()});document.querySelectorAll('[data-package]').forEach(el=>el.onchange=()=>{wo.find(i=>i.id===el.dataset.package).package=el.value.trim()||'Paket 1';renderWo()});document.querySelectorAll('[data-remove]').forEach(el=>el.onclick=()=>{wo=wo.filter(i=>i.id!==el.dataset.remove);renderWo()});total()}
function download(kind,data){const project=$('#projectName').value.trim(),contract=$('#contractNo').value.trim();if(!project||!contract){status('Isi nama project dan nomor kontrak sebelum menyimpan draft.');return}const payload={format:'bima-operational-draft-v1',kind,project,contract,contractType:$('#contractType').value,currency:'IDR',sourceFile:sourceName,sourceSheet:$('#sheet').value,createdAt:new Date().toISOString(),...data};const url=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='operational-'+kind+'-draft.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);status('Draft JSON diunduh. Belum disimpan ke Supabase.')}
$('#exportMaster').onclick=()=>download('master',{items:parsed.items,warnings:parsed.issues,skipped:parsed.skipped});$('#exportWo').onclick=()=>{if(!$('#woNo').value.trim()||!$('#woTitle').value.trim()){status('Isi nomor dan nama WO.');return}download('wo',{number:$('#woNo').value.trim(),title:$('#woTitle').value.trim(),items:wo})};renderWo();
window.addEventListener('beforeunload',e=>{if(parsed.items.length||wo.length){e.preventDefault();e.returnValue=''}});
